# Generated by Django 3.1.4 on 2020-12-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500, verbose_name='First name')),
                ('last_name', models.CharField(max_length=500, verbose_name='Last name')),
                ('experience_years', models.IntegerField(verbose_name='Years of experience')),
                ('date_created', models.DateField(verbose_name='Date consultant was added')),
                ('date_updated', models.DateField(verbose_name='Date of last update')),
            ],
        ),
    ]
