# Generated by Django 3.1.4 on 2020-12-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0001_initial'),
        ('consultant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='practice_areas',
            field=models.ManyToManyField(to='expertise.PracticeArea'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='skills',
            field=models.ManyToManyField(to='expertise.Skill'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='specializations',
            field=models.ManyToManyField(to='expertise.Specialization'),
        ),
    ]
