# Generated by Django 3.1.4 on 2020-12-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0001_initial'),
        ('consultant', '0002_auto_20201206_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='consultant',
            name='form_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Date consultant was added'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='Date of last update'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='practice_areas',
            field=models.ManyToManyField(blank=True, to='expertise.PracticeArea'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='skills',
            field=models.ManyToManyField(blank=True, to='expertise.Skill'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='expertise.Specialization'),
        ),
    ]
