# Generated by Django 3.1.4 on 2020-12-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0003_auto_20201208_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='day_rate',
            field=models.IntegerField(default=500, verbose_name='Daily rate in PKR'),
            preserve_default=False,
        ),
    ]
