# Generated by Django 3.1.4 on 2020-12-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0004_consultant_day_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='previous_engagement',
            field=models.BooleanField(default=False),
        ),
    ]
