# Generated by Django 3.1.4 on 2021-06-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0005_consultant_previous_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='query_score',
            field=models.IntegerField(default=0),
        ),
    ]
