# Generated by Django 3.1.4 on 2021-06-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0006_consultant_query_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='query_score',
            field=models.FloatField(default=0.0),
        ),
    ]
