# Generated by Django 3.1.4 on 2021-06-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0007_auto_20210602_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='query_score',
            field=models.IntegerField(default=0),
        ),
    ]
