# Generated by Django 3.1.4 on 2021-06-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0008_auto_20210602_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Consultant's email address"),
        ),
    ]
