# Generated by Django 3.1.4 on 2021-06-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0009_consultant_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultant',
            old_name='cv_file',
            new_name='cv_file_1',
        ),
        migrations.AddField(
            model_name='consultant',
            name='cv_file_2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='consultant',
            name='cv_file_3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
