# Generated by Django 3.1.4 on 2021-07-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0011_auto_20210706_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="Consultant's email address"),
        ),
    ]
