# Generated by Django 3.1.4 on 2021-07-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', 'Trigram_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date_of_engagement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Year of engagement'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='project_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='OPM project code'),
        ),
    ]
