# Generated by Django 3.1.4 on 2021-06-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20201213_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date_of_engagement',
            field=models.TextField(blank=True, null=True, verbose_name='Year of engagement'),
        ),
    ]
