# Generated by Django 3.1.4 on 2021-06-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20210602_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='creator',
            field=models.CharField(max_length=500, verbose_name='Your name'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_of_engagement',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Year of engagement'),
        ),
    ]
